extends:
  - prettier
plugins:
  - prettier
env:
  browser: false
  es6: true
  node: true
rules:
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: es5
      bracketSpacing: false
      jsxBracketSameLine: true
      tabWidth: 4
      printWidth: 80
      semi: true
  no-plusplus: ["error", { "allowForLoopAfterthoughts": true }]
  no-use-before-define: ["warn"]
  no-warning-comments: ["warn", { "terms": ["todo", "fixme", "xxx", "to do", "fix me"] }]
  global-require: off
  no-console: off
